name: Complete testing

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
      - run: poetry install --with dev
      - name: poetry test
        run: poetry run pytest