name: Testing

on:
  workflow_dispatch:
  push:

jobs:
  pytest:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install --with dev
      - name: poetry test
        run: poetry run pytest