name: Complete testing

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10','3.11','3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: poetry install --with dev
      - name: poetry test
        run: poetry run pytest