name: Testing

on:
  workflow_dispatch:
  push:

jobs:
  pytest:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run image
        uses: abatilo/actions-poetry@v2
      - name: poetry install
        run: |
          poetry lock
          poetry install --with dev
      - name: poetry test
        run: poetry run pytest